@startuml DataObject
skinparam classAttributeIconSize 0
package BusinessIntelligence {
    interface CloudClient {
     +exists(name: String): Boolean
     +create(name: String): File
     +download(name: String): File
     +publish(name: String): String
     +delete(name: String, recursive: Boolean): File
    }

    class DataObject {
     -bucket: String
    }

    class Exception
    class ObjectNotFound
    class ObjectAlreadyExists
    class UnexpectedResponse

    CloudClient <|.. DataObject

    Exception <|-- ObjectNotFound
    Exception <|-- ObjectAlreadyExists
    Exception <|-- UnexpectedResponse

    DataObject ..> ObjectNotFound: Throw
    DataObject ..> UnexpectedResponse: Throw
}

package AmazonSDK {}

BusinessIntelligence ..> AmazonSDK: Imports

@enduml
