@startuml DataObject
skinparam classAttributeIconSize 0
class DataObject {
 -bucket: String

 +exists(name: String): Boolean
 +create(name: String): String
 +download(name: String): String
 +publish(name: String): String
}

class Exception
class ObjectNotFound
class UnexpectedResponse

Exception <|-- ObjectNotFound
Exception <|-- UnexpectedResponse

ObjectNotFound <.. DataObject: Throws
UnexpectedResponse <.. DataObject: Throws

@enduml
