@startuml DataObject_Download

actor User

participant "BI_AWS_ELIXIR" as App
participant "AWS S3" as S3

User -> App: start application
User -> App: enter file name
App -> S3: check if file exists in bucket
S3 --> App: return boolean indicating whether file exists

alt file exists
  App -> S3: get object
  S3 --> App: return object
  App -> User: display object
else file does not exist
  App -> User: display error message
end

@enduml
