@startuml DataObject_Exist

actor User

participant "BI_AWS_ELIXIR" as App
participant "AWS S3" as S3

User -> App: start application
User -> App: enter file name
App -> S3: check if file exists in bucket
S3 -> App: return boolean indicating whether file exists
App -> User: display result

@enduml